---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempdownloads
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 200Gi
  storageClassName: openebs-hostpath
