---
apiVersion: v1
kind: Service
metadata:
  name: &app s3-minio
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: "10.26.10.20"
  ports:
    - name: http
      port: &port 9000
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app s3-minio
  namespace: network
  annotations:
    hajimari.io/icon: mdi:home
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: internal
  rules:
    - host: &host "s3.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 9000
  tls:
    - hosts:
        - *host
