---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: manyfold
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: manyfold-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MANYFOLD_SECRET_KEY: "{{ .manyfold_config_secret_key }}"
  dataFrom:
    - extract:
        key: manyfold
      rewrite:
        - regexp:
            source: "(.*)"
            target: "manyfold_$1"
