apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wT6jWmgv9b1+ovau+oBMRQphAmrTae7CwnbD4km8S++K1R+5,iv:hhffcpbV7tMDiaeta37ylyihYNWPKLTCaFkm8yIK1jU=,tag:WEJ8/cJENHpO8H/gxEfiqQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:H5nU5sg61gzf3KX5j0DujkrSA1t1I/bUbzy8S5PKT88Y0C31x8zuyqxHUgA3X30WOmLe60SoR/LeoIk3jzXpB2L/GHRXi264FMCf22K/liH8gpu7f1iLm3bH3vif8Zh6MpyjAulgPygHtf35PeWQyX98e85kNzE5o4PK6XbrlncAFTWPkKZjxHfAzgczMHLHsRHZdyli1nvATIzovlNaiadl0E85uXYl3+tgGGdihg==,iv:d2PT7f8Uh8PtM6T9XG/sQxr/TaQofum4lqttxu99dtM=,tag:MO4jNaum1AqaWhvaUtEkjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q685ed22suytjulg8sn88972uj6cjktwxstpljjftjwh2xmd43qqk9c36g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaHVRbi9iQVpscmJCMHlC
            MUlWRWRHWG05QUNUYVBGRW9XVzlhcVpsWkhJCnZBWGczbkRXTHRCa3c5amc0VmZR
            VDlJMGJNYnI4WDlWWUg3NmpuT05ORDAKLS0tIFFoVTIzMUdUMlNIVTBTcWxCdEVw
            WHpoUmtSZGpka1hrOStBZU5samM1bncKP06Qxehq+bBDVhRTr0RsVIGDbmkBk6Ke
            WjLoUgn2wxZBfBIhNTdne+IVeUDZ0Qik+RsAVPjmF/vSRu7m3RV10A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-09T01:36:36Z"
    mac: ENC[AES256_GCM,data:ur97sahcQn19RUTz3RbJgJvC8Gt/fWH1Zvl2JgNgj41sJx2ZMxzv/PXbH2PXRzh6QqUVZWrhayYDVML+xrc4FoLlWImqL+9cYT+PzIRNBOx96HbxRh8mBJT8LCPrJy1fqq2hjWn6LXjQtJBhQnAvWuJGEMi9JQTC4jrjZK6MG+E=,iv:h59Ij6otIZI0oblBnBUV+HSUkNTZCkAyqdxdwhaUmsQ=,tag:cIdlVvAlNgH0dXy9+8oRzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
