apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5ikH8LBIpNuDe21UTG4N7k1VxZ3yLUN5ha57pQ51USWT06rot3siKA==,iv:X1/2FEMzq5zvJ8+tJLv8QIXi8gen+nQvDMcCS11kXtI=,tag:RRSZKDLmj6maxGvizWyQGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q685ed22suytjulg8sn88972uj6cjktwxstpljjftjwh2xmd43qqk9c36g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRzJId050eXdkQTBiVCtN
            WkJoOWROKzJpQi9meWRpUm15dG9WOEVxeVdJCnFROXl4dHdpeTZ0bXh2WU1PRnlL
            aGR1SVlZcHFDcmhYRk9nU3FKWHhJZG8KLS0tIEs4dXFGVHBMY3V6RFpwbHFodDBX
            SDZONnU0NWxGVkoxb3FETFF4VEtHcVUKPYulJ/8oGh3vESHN4btRPT1O5CQiBIgE
            pa1DGK63HrnpyiNZANFLpc3qiY0HhZ9c50mQq+WCc1xAZq0BI/fudA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-17T01:25:24Z"
    mac: ENC[AES256_GCM,data:n5h5R9v/eDYKfp3t+bHes5vyqaUj4f9WbNahJru8G8Sj8vkD4IAH8BD6G2ImNARIXx9wzsV+Ur/6e6wGv0+XRb/+1uAzk779J+1Nr/zVm9RTJ64N/sBVwDZulyZQxr4ZQz9Wyut11A+YSzzh3XMAeqaWQ9v0OSb4e5JX3qCi28Q=,iv:ALwI3Y9x2s7leKsFWuoFHSUkefud1qAmoIR9mTL5Fok=,tag:Kh6bqjO8DL0PZLB4Jy1RdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
