---
apiVersion: v1
kind: Namespace
metadata:
  name: selfhosted
  annotations:
    volsync.backube/privileged-movers: "true"
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    volsync.backube/privileged-movers: "true"
