# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-secret
data:
    clients-info.yaml: ENC[AES256_GCM,data:sJX8KEWBPq8IQHvfrK1qSrUsk59Nj7ztGkW0PzksfkXBW88KF4WYUh9J95K34QbgLwdYJgqxR4l+hA699l2DH0v9CavRxXo4tG5PVbgodbP8Y6v9KfSNACl+i0Ax6yU7j6eSVq3gfg==,iv:Z0ayaPEfCPqJC18OXjacwmwu6o73wxDqXv1pU4gW1LU=,tag:FyS1LqAEXZEIlYE4LY0gZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q685ed22suytjulg8sn88972uj6cjktwxstpljjftjwh2xmd43qqk9c36g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SWFvNHBkQ0ZNSVBvV05B
            YkhVNHV5bGdtNWhUVDBIYm9JZFJCc2NsZDNJCisvMVErQ2VhUytBeUlqQzVZeTlD
            Z3AyS01Pa2x5QWNaR3BuTEl3UGNIY3cKLS0tIG1SczU4Zk5mRXZ4TUxHUFh3ZlZy
            cVpkeUt0eEMzTUxIeWNRMncvWTRmREEKsA8rNs3NaKhGuz3+LOAicic4nv9sw33t
            vbm5XT0ngvXhOoNKG0Nzvce4TeinFm1QC1fJmsxFvc3JEXJ/w2wjGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-20T19:38:15Z"
    mac: ENC[AES256_GCM,data:jOdNHRQm2SY+uVEcP19qZKBbcFSyv+VU1wdxj5EiUz9wqqecLBbjnJXsOsl5ypYjTAxjNVzbbCi41amvASgV03rMv/cg1dzjZG4GsIEuZNeOqWuUIKPI27T9CcQ4F18xPHbp0p30arWKSjTCJqSzcTzKL/9ge4O3xx0GOK0VfSQ=,iv:8LPV75z5u/GEcMWxvl6qDQ6aG1idB5XI9Qnqn/ihhsE=,tag:hoymZX+5wyOqT3guLsIpTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
