# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
stringData:
    clients-info.yaml: ENC[AES256_GCM,data:TtPLTfRPf6+Cg+fKlW7OIxYKw2C6vwv/02RsdRzS3O4gzlm9CrnWAcWDypq0gLwhjxtfP07DnieeRE3WUqggO9iA+BzBT0klFmeWPPwn5wmSE9atrAe47Oe/+6rp20QKsDWXYi3hkA==,iv:noVrnRobQBb/h/d/FFoJTSQkBC1CZxnif4nH5+kiJ3g=,tag:JqDsyCfeFpEiPuOFPkrkjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q685ed22suytjulg8sn88972uj6cjktwxstpljjftjwh2xmd43qqk9c36g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SWFvNHBkQ0ZNSVBvV05B
            YkhVNHV5bGdtNWhUVDBIYm9JZFJCc2NsZDNJCisvMVErQ2VhUytBeUlqQzVZeTlD
            Z3AyS01Pa2x5QWNaR3BuTEl3UGNIY3cKLS0tIG1SczU4Zk5mRXZ4TUxHUFh3ZlZy
            cVpkeUt0eEMzTUxIeWNRMncvWTRmREEKsA8rNs3NaKhGuz3+LOAicic4nv9sw33t
            vbm5XT0ngvXhOoNKG0Nzvce4TeinFm1QC1fJmsxFvc3JEXJ/w2wjGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-20T19:24:35Z"
    mac: ENC[AES256_GCM,data:TVrOAzyPJKdasbJ8Uq9E5+d72GGDdOpCWCDUBFVwhJbOp6oOYJD/yENDeHOTtXQGiZ/lMYYuzBtfKTQrdD9rgBAlsbFgYx0Yx2Ljna/NiT8qeY040bPllSiUnZdLDQZh4ajBObSm999r40aVAFSrW2dM/nlwc5G2BxkgOvoYFJM=,iv:UenT7VmjHDjtTusfEx+DMbxpZmGXaIf4iS2myCVE6JM=,tag:pCtGFXVVIteDcp9//iLs3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
