---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-csi
provisioner: csi.san.synology.com
parameters:
  fsType: brtfs
  location: /volume3
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
