apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:SXpCZLMqQW5Kew==,iv:rCWnClKDMZz3+lniZ8ZFKeoZi3NJ70ZqkD0qJqKcvBE=,tag:Q981u2jKCZC6JmSkObGTyQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ml71f+uDfpDTQQKPyxUpnUb0fA==,iv:LgrT1GlaiLu0DTGQCaaUkA4Xl4Z5CrhlhHtgrs4OCwU=,tag:6LQciwsDs8QjRlOfAhGsWA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:kEOK9e2xBFJJqrjgQ/A13V9XLSdl936WA7sS/oWzX72IVJ4i,iv:Yw+t69dVnkHZsoFPRflvXpDngyJhq09jP5wWpTEFAo4=,tag:N/+T/GMDCQpL5PQomWiW/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q685ed22suytjulg8sn88972uj6cjktwxstpljjftjwh2xmd43qqk9c36g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYnJSZDNEenFCaC9ybWFH
            QnBTUVB2YjAxVmFSTDJHeWtnamJPM01GZGxZCnIrSzhmOWdpT2pxeFJBYy9yVVpy
            Wm9yTHk4UGlsMlI1ZTZJSHNEQ3BKWUEKLS0tIHo5K2Jlc2hqeFBhbnNvcHlhRzA5
            bnV5bWZvcTNER1dxSjQ2WXNHTUNMTkkKmt+2O6tIX0uEsELT1McMEWbYWZLwzXK9
            B2gOfc1QE9rLD5FvhV8MB4b1VA1gw6mo/+1vY4pEanHGI5A1GCjv+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T03:56:05Z"
    mac: ENC[AES256_GCM,data:vF0MwDnfdI4/xd2re8+cgRlbAV1MwzmsyNqnLGyeAk+8dmNkbu/8weiMzh/RhJddPwgsHWghyrvvGJhgBxMmRdyAxVu8bxTD6MryvzG4NWtFK4C8nWJ2ZAiwzDEIvjcgAoD5KakHqfKsoGHzD3cZqlAkWk6vA4uBJ4eQz8et35g=,iv:hjk/VRqeTH68k3F7nCoXAsVijlTjucasfS53RxfsCVk=,tag:4MwYqcZ7uwidPbRl5JLw7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
