---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      syncthing:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: syncthing/syncthing
              tag: 1.29.2
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                memory: 100Mi
              limits:
                memory: 200Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: syncthing
        ports:
          http:
            port: 8384

      listen:
        controller: syncthing
        type: LoadBalancer
        loadBalancerIP: 10.26.10.120
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-sharing-key: syncthing
        ports:
          listen:
            enabled: true
            port: 22000
            protocol: TCP
            targetPort: 22000

      discovery:
        controller: syncthing
        type: LoadBalancer
        loadBalancerIP: 10.26.10.120
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-sharing-key: syncthing
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027

    ingress:
      app:
        className: internal
        hosts:
          - host: "sync.donohoo.io"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      media:
        enabled: true
        type: nfs
        server: 10.26.10.20
        path: /volume1/syncthing
        globalMounts:
          - path: /var/syncthing
