apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ZYn5a5iX6FSa9GQdB5py2uxCNHOiaX955vdUXNphFjg=,iv:4I/i/HunCC3U/99HnEazge3EhDE1WdYdU09bkPF+/xw=,tag:xoe1HrE/KCeHG+loFxNM3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q685ed22suytjulg8sn88972uj6cjktwxstpljjftjwh2xmd43qqk9c36g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K2RBaEFzcE1QUytLOXpV
            K2dmZTRoa0tpSGlFcmQybldSQVVqTWhGcW13CkV5Kzdzd01XcDE5NTlYVlI1UXQx
            cC9udktselN3VmxYYkJ2RVFhSjhveTAKLS0tIHdFWUlnTHhOUkUrUDcwUnZQTXZI
            OHh0K0tFMzU4bVhudjNQY2pEQStiK28KyyKVs6IgsB7I3eW74f8QSeKx8YSPzgFu
            S05oi2l4eV80j/sRSOI4IwLLLs5YexQJaDFU0bnvQ76xqopp3lcD7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-17T01:15:22Z"
    mac: ENC[AES256_GCM,data:9JlyDWtW9QwUevtZ6W6DxnoqXrT6AP9eyjuVOHqjNpU4N5iN6NlRYD7FjVhDDh85S6P1YI+YZPkjvkgz+YtD0gtpMFRkJ38UFJ99D0qHTDgJFY+h0GBVQOJh9ctoR3Q58yPBWqsmjObSn2gkCn5Ukb1oBhfxfF029zksFU+M44c=,iv:qtVpiyG4V/p0iuf/5YlXsmzWDYlPuvOS3wl6doVbTg4=,tag:ZQxGeTQ2TZqgHvOhkgXxTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
