apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:B5vsZ+8ioJ5YClnJencC16pRW5DEhLreB8p+0jGpL0EcjfcTEPYqsw==,iv:fsMqxjuLMPa3ThBpOptHUopv41omiO8ypnDWQkG+tJY=,tag:f4zpCnIaO3wjxBUjcxhTrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q685ed22suytjulg8sn88972uj6cjktwxstpljjftjwh2xmd43qqk9c36g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUFRTM3NKeVhGL1JnRUk1
            eFRlSnFZTVl2TmNXeGFJSGp1dmJHb08wNEdVCjk5bG9TdS91M0dPMDBxcXZRYnFy
            aDNrRHBUdjNVSlNwQy9CdmZLajdlREkKLS0tIHQ2ZjNBTW5sZ3UvMFFxM1ZubW0z
            Tk9qQlF4a0p2K29vYmczKzZZc1Y2bGcKOcHvxRpcdkU6SQwGNb0dMQw+cPCW3pzh
            TsfMhrHpYBGiebftvrDyvCPLP1L/6SwUgxbXAyoTaft/ePJOC2dnKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-17T01:15:22Z"
    mac: ENC[AES256_GCM,data:4vcAPP96Mg2sqd+LBJzudfONrzSsWR6TNIItKbs7MywyfPeKxHU4u3+sWedm67aMfvq8SL648W5Nm5n+aZypQdK13eq4BT0Vgwd59vdI9SLzKVzb3zKJFMoWzWqBl/6oAd/JqxUY1296mggSCAcSDuRo01VX7H73i1/5+qB22lE=,iv:onSYteCD0DTR2AMol0Nmga6WunqyZSX0yXGiH33IDLQ=,tag:RIUaOOJv1XISyl7xBesLYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
